[workspace]
resolver = "3"
members = [
    "crates/dns-proto",
    "crates/dns-zone",
    "crates/dns-cache",
    "crates/dns-resolver",
    "crates/rdns",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
dns-proto = { path = "crates/dns-proto" }
dns-zone = { path = "crates/dns-zone" }
dns-cache = { path = "crates/dns-cache" }
dns-resolver = { path = "crates/dns-resolver" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "io-util", "signal"] }
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = "thin"
